// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaccythzxwbwwukphjmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhY2N5dGh6eHdid3d1a3Boam1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODQxNzQsImV4cCI6MjA3NDY2MDE3NH0.qYEvX0UkN4EH0thXfxPBBDiL5Jy1zTYxzD-cBFM-XoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});